name: CI/CD Pipeline
on:
  push:
    branches:
      - develop

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: |

          npm run test:coverage

          # Save coverage report as artifact
          mkdir coverage-artifacts
          cp -r coverage/ coverage-artifacts/
    - name: Upload Coverage Artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage-artifacts
    - name: Deploy
      run: npm run deploy
    - name: Build Docker Image
      run: docker build -t proyectosoft2:latest .
    
